### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by chenchen923** [tommi-fish/SkinPort-Discount-Check#1]
Dear author, hello, when I ran main.py, the error message shown below appeared. I have installed creds and need your help!
![Snipaste_2024-10-21_08-12-11](https://github.com/user-attachments/assets/9aeea5d3-473f-4a4f-8e04-a684e89d49a0)

**Comment by tommi-fish** [comment]
Please see new readme for instructions, code is alot easier to run now :D
